### ISSUE TITLE
Restrict search area

### ISSUE THREAD

**Issue by bikeoid** [mecatran/OpenTripPlanner-client-gwt#1]
Restrict search area to the bounds served by the specified OTP instance so that matches are displayed from that region instead of worldwide

**Comment by laurentg** [comment]
Which search are you talking about? By default the geocoder do use bounds information to restrict the search; default map display also use the bounds. Default bounds are returned dynamically by the server.

**Comment by laurentg** [comment]
Closing stale issue.
