### ISSUE TITLE
Impossible to set a stop point in a zone whereas no bikeshare station is present, when bikeshare activated

### ISSUE THREAD

**Issue by kalon33** [mecatran/OpenTripPlanner-client-gwt#4]
When planning a trip using this OTP interface on my OTP instance (http://plannerparis.acolytesanonymes.org), I can't set a endpoint (or a startpoint) on the map in a zone where no bikeshare station is available (bikesharing activated), whereas it is near a bus stop (I have no problem planning such a trip using the original web interface (see http://paris.acolytesanonymes.org).

This seems to involve only geocoding as both transit and bike sharing and transit modes are affected.

It did not happen when bikesharing was disabled on the OTP instance.

**Comment by laurentg** [comment]
@kalon33 Again, I tested and did not have problems setting start/end points and planning on a zone without any bike-share stations. What do you mean by "can't set"? Do you have a specific location? This may be specific to certain zones; I'm not sure it's related to bike-share.

**Comment by kalon33** [comment]
@laurentg are you using Firefox too? That might be a browser problem? I'm trying to plan a "la glacière, Paris" to "avenue du général de gaulle, longjumeau" trip using the map

**Comment by laurentg** [comment]
@kalon33 Firefox on Linux, yes. The plan "la glacière, Paris" to "avenue du général de gaulle, longjumeau" works fine for me, but be careful: you have to select an origin and a destination on the list.

**Comment by laurentg** [comment]
@kalon33 Ha I see what may be your problem: do you click on the "plan route" button before unfocusing the field "destination address"? For geocoding you have to select a proper proposal; otherwise the plan won't work.

**Comment by kalon33** [comment]
@laurentg did you try by selecting them on the map instead of typing them in the search fields? Doing that, I can't set my endpoint in Longjumeau.

**Comment by laurentg** [comment]
@kalon33 What do you get as error? I just tried myself, clicking around Longjumeau works fine...

**Comment by kalon33** [comment]
@laurentg BTW, the geocoding system used by that project (https://github.com/flibbertigibbet/opentripplanner-mobile-site) is much more convenient as addresses can be typed using a number, it is fast and more accurate even when request is not "perfect".

**Comment by kalon33** [comment]
@laurentg I got no error at all, I'm just unable to set and endpoint or startpoint on the map that's not near a bikeshare station, even in transit only mode.

**Comment by kalon33** [comment]
@laurentg nothing changes in the interface, like if I didn't perform any action.

**Comment by laurentg** [comment]
@kalon33 Does setting the start/end point by clicking on the map never works or works certain times? Normally when you select the start/end point on the map you have a reverse-geocode call made, and the address field is filled-in accordingly. Then if both start and end point are defined, a route plan call is made.
Which browser/OS do you use? Can you check on the browser log if there is anything suspicious, especially regarding the reverse-geocode?

**Comment by kalon33** [comment]
@laurentg it never works when I try to reverse-geocode outside the bikeshare stations area, but always when I do this in the bikeshare stations area.

I use latest Firefox on Ubuntu 15.10 beta.

When I try to set an endpoint outside the bikeshare stations area, here is the error I have in the browser log:

Blocage d'une requête multi-origines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://nominatim.openstreetmap.org/reverse?format=json&addressdetails=1&lat=48.69626255506664&lon=2.2967897197265996. Raison : l'en-tête CORS « Access-Control-Allow-Origin » est manquant. <inconnu>
Blocage d'une requête multi-origines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://nominatim.openstreetmap.org/reverse?format=json&addressdetails=1&lat=48.69626255506664&lon=2.2967897197265996. Raison : échec de la requête CORS.

**Comment by kalon33** [comment]
@laurentg  I wanted to also try on an iPad but couldn't set start/end points on the map (couldn't trigger the menu to set them)

**Comment by laurentg** [comment]
@kalon33 I think this is the issue: reverse-geocoding on Nominatim does not seems to work on your machine. This is strange as it works fine for me on Firefox 41.0.1 / Debian. It could be a configuration issue on some plugins. Do you have "HTTPS Everywhere" enabled on your firefox?

**Comment by kalon33** [comment]
@laurentg yes, I have it enabled. Is this the culprit?

**Comment by kalon33** [comment]
@laurentg it seems to be the culprit, I tested in chromium without bugs. I disabled some rules in HTTPS Everywhere in Firefox (notably Openstreetmap ones) and that makes things better.

Doing that, I discovered a missing thing in both browsers (Firefox and Chromium): Print itinerary is not working, and triggers that error: 
uncaught exception: com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : a is undefined

**Comment by laurentg** [comment]
@kalon33 OK, it's a known bug in HTTPS everywhere (https://github.com/EFForg/https-everywhere/issues/49). I'm closing the issue, can you re-open a new one for the print issue?

**Comment by kalon33** [comment]
@laurentg just opened #6 :) Thanks for your help on this :)
