### ISSUE TITLE
Improve geocoder using ideas from other projects

### ISSUE THREAD

**Issue by kalon33** [mecatran/OpenTripPlanner-client-gwt#5]
The current geocoding system is not really easy to use to accurately find proper start/end points.

Other projects have very nice systems, like the geocoding system used by that project (https://github.com/flibbertigibbet/opentripplanner-mobile-site) that is much more convenient as addresses can be typed using a number, it is fast and more accurate even when request is not "perfect".

**Comment by laurentg** [comment]
@kalon33 Do you know which geocoder they use for this projet? Adding a geocoding in the projet is rather simple, it only needs a class implementing the `Geocoder` interface, and configuring it by some means.

**Comment by kalon33** [comment]
@laurentg According to the code here: https://github.com/flibbertigibbet/opentripplanner-mobile-site/blob/develop/js/otp.js
It is mapbox, but infortunately, I don't know much in Java to implement this...

**Comment by laurentg** [comment]
@kalon33 Without the "https everywhere" bug, I think this issue may be closed too?

**Comment by kalon33** [comment]
@laurentg if it is not planned to add a way to choose between geocoders and add this one, maybe.

**Comment by laurentg** [comment]
@kalon33 Well, it's not planned, especially that the geocoder we use by default (OSM nominatim) and the Mapbox one are really similar. I do not see many added value to add it (altought it should not be that difficult).
Closing the issue.
