### ISSUE TITLE
Impossible to print itineraries using the "print itinerary" function

### ISSUE THREAD

**Issue by kalon33** [mecatran/OpenTripPlanner-client-gwt#6]
I discovered a missing thing in the interface: Print itinerary is not working, and triggers that error:
uncaught exception: com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : a is undefined

**Comment by laurentg** [comment]
@kalon33 Can you check if you still have the problem? There was some issues that were caused by a plugin on firefox.

**Comment by laurentg** [comment]
Closing stale issue.
