### ISSUE TITLE
OpenTripPlanner-client-gwt doesn't work anymore under OTP 0.19.x

### ISSUE THREAD

**Issue by kalon33** [mecatran/OpenTripPlanner-client-gwt#9]
Under OTP 0.19.x, "/otp/routers/router_name/metadata" was removed, and seems to be replaced by only "/otp/routers/router_name".

A change to src/main/java/com/mecatran/otp/gwt/client/proxies/otp/OtpPlannerProxy.java is needed to fix the problem, and allow the interface to run. This fix is available in PR #8.

**Comment by laurentg** [comment]
Fixed by PR #8.
